### ISSUE TITLE
Attribute v0 and NEURON mechanisms not found in /home/jovyan/neuronunit/NeuroML2.

### ISSUE THREAD

**Issue by rgerkin** [russelljjarvis/neuronunit#12]
@russelljjarvis 
I did a lot of cleanup and integration work and things are mostly running except now I am getting an error in NEURON:
```
  File "/home/jovyan/neuronunit/neuronunit/tests/NeuroML2/LEMS_2007One_nrn.py", line 52, in __init__
    h.m_RS_RS_pop[i].v0 = -60.0
AttributeError: 'NoneType' object has no attribute 'v0'
```

You can see the full build [here](https://travis-ci.org/scidash/neuronunit/builds/217902470)

Do you know what is causing this?

**Comment by rgerkin** [comment]
I actually meant to post this in the `scidash/neuronunit` issues but accidentally posted it here.  It refers to the `scidash/dev` branch, not the `russseljjarvis/dev` branch.

**Comment by russelljjarvis** [comment]
Yes I can see what the problem is, its that the NEURON mechanisms are not being compiled. Ie its the same problem we saw when we where both working in the office last.

If you scroll up a bit from the stdout in the travis you linked to you can see a more fundamental error:
NEURON mechanisms not found in /home/jovyan/neuronunit/NeuroML2
when it says the mechanisms where not found, it means that jNeuroML did not make *.mod files. 

I am unsure why jNeuroML was not called at least once, the absence of a functioning jNeuroML call in the condition that no mod files exist is the reason for this problem.
```
NEURON mechanisms not found in /home/jovyan/neuronunit/NeuroML2.

NEURON: RS is not a template

 near line 1

  RS_pop[0]  { m_RS_RS_pop[0] = new RS(0.5) } ```

**Comment by russelljjarvis** [comment]
I think the problem is that the condition on 249 of [backends](https://github.com/scidash/neuronunit/blob/dev/neuronunit/models/backends.py#L249
) is too easily satisfied.


It currently reads:
`if os.path.exists(self.orig_lems_file_path)`

but it should read like this instead:
`if os.path.exists(self.orig_lems_file_path+str('/x86_64')):`

**Comment by rgerkin** [comment]
Let's see if 99267f8f6 does the job.  It is using `platform.architecture()` to get the value x86_64, which could be different on a different system (e.g. 32-bit, RISC, ARM, etc.)

**Comment by russelljjarvis** [comment]
Oh yes thats a good point that the directory is architecture specific.

**Comment by rgerkin** [comment]
Seems fixed.

**Comment by russelljjarvis** [comment]
great yes.

**Comment by russelljjarvis** [comment]
I think its almost fixed but not quiete.

Now it does not see the architercture directory and builds JneuroML and recompiles mod files every time.
```
> /home/mnt/neuronunit/models/backends.py(140)load_model()
-> if os.path.exists(NEURON_file_path):
(Pdb) NEURON_file_path
'/home/mnt/neuronunit/tests/NeuroML2/LEMS_2007One.xml/x86_64
```
The reason is the .xml file type extension is still in the path.

I propose adding in these extra lines will strip out the xml extension:
```
filename, file_extension = os.path.splitext(self.orig_lems_file_path)
NEURON_file_path = os.path.join(filename,architecture)
```
I am testing now, unsure if it works or not yet.

**Comment by russelljjarvis** [comment]
In fact the above is not even specific enough. I had to do a lot of string manipulation in order to get the right path:
```
        filename, file_extension = os.path.splitext(self.orig_lems_file_path)
        k=str('/')
        filename=str(filename).split("/")
        for i in filename[1:-1]:
            k+=str(i)+str('/')
        filename=str(k)
        NEURON_file_path = os.path.join(filename,architecture)
```

**Comment by rgerkin** [comment]
More elegant:
```
LEMS_dir  = os.path.dirname(self.orig_lems_file_path) # Gets full path to directory with file.  
NEURON_file = os.path.join(LEMS_dir,architecture)
```

**Comment by russelljjarvis** [comment]
Are yes thats much better.
