### ISSUE TITLE
avoiding collisions between different CPUs reading and writing from the same file.

### ISSUE THREAD

**Issue by russelljjarvis** [russelljjarvis/neuronunit#24]
Is the use case for tempfile to avoid such collisions, or was it designed for something else?

My not graceful approach was to create process dependent file names such as below, however the list of filenames grows quickly, and I don't want to write code that cleans them up, since I shouldn't have created  them in the first place.

What I really want, is one file, many context dependent file objects to scatter across the dview.

```python
        file_path = str(get_neab.LEMS_MODEL_PATH))
        scatter_file_objects = [ open('file_path','r') for i in range(0,len(dview)) ]
        dview.scatter(fo,scatter_file_objects)
```

and I want to be able to use the file object in the model construction instead of a pathname

```python
        model = ReducedModel(fo,name=str('vanilla'),backend='NEURON')

```
Instead of:
```python
        model = ReducedModel(path_name,name=str('vanilla'),backend='NEURON')

```

**Comment by rgerkin** [comment]
@russelljjarvis I agree that would make more sense (to use a file object instead of a path), but I did not know a way to get N independent file objects, one for each processor, that could be read/written independently, so I just have it creating N temporary files instead, which I think achieves the same basic goal.  The number of actual file reads/writes shouldn't be very large anyway, except for via the jNeuroML backend where we have no expectation of speed (and no alternative to reading directly from files).  

You shouldn't need to cleanup the temporary files.  The OS expects that they can be scrubbed at any time, and for that matter you personally can `rm -r /tmp` if you are worried about it.

**Comment by russelljjarvis** [comment]
AOK. 

It turns out we have been studying this issue in C# sharp in the distributed programming unit I am taking.

It turns out that 

Parallel reads are collision free.

Parallel writes collide.

Simultaneous reading and writing from the same file collide.

In theory I think the parallel GA only needs to do parallel reads, which should not collide
My parallel scoop version of the program never had this problem. I suspect somehow by switching from the SCOOP to the ipyparallel implementation, both of the scidash and the russelljjarvis versions of the optimizer are doing unnecessary file writes.

This may be related to redundant calls to jNeuroML.

**Comment by russelljjarvis** [comment]
This problem goes away when NEURON parallel implementation is appropriately un coupled from jNeuroML, excluding a single bootstrapping call.
