### ISSUE TITLE
docs/*hapter5* need to be consolidate into one file

### ISSUE THREAD

**Issue by rgerkin** [russelljjarvis/neuronunit#27]
There are many versions of \*hapter5\*, including: 
- chapter5.ipynb
- chapter5.py
- Chapter5.ipynb
- Chapter555.ipynb

Delete all but one of these (chapter5.ipynb), keeping in it what you want to be in that chapter.  It is OK if it doesn't actually run for now, as we can fix that before the merge to scidash/master.  Consolidation needs to be done before the pull request is accepted.

**Comment by russelljjarvis** [comment]
I deleted all of them since they either used scoop as a backend (and therefore possibly may not even work, or if they did, they would be unsupported, or they had cluttered import statements).  These files will be staged in my own commits on GH dating before the 9/22nd (22nd of the 9th). 

I think a better way of moving forward is to write unit tests first and make the notebooks second.
